Feature/add chainlink
scroll-tech/scroll-documentation pull request #322
Opened 2024-08-23 15:52 UTC by melchermaxwell

## Closing issues

## Description

Add Chainlink to the Scroll Developer tools

## Changes

-added chainlink.mdx with relevant info

2024-08-23 15:55 UTC, dghelm commented
Glad to see Chainlink added here! Wondering if we could provide useful information for Scroll devs, since only a subset of Chainlinks docs are relevant to developers.

Could we provide LINK token address, Sequencer Uptime Feed address (or direct link) along with a pricefeed link for Scroll?

2024-08-23 19:38 UTC, thedriftofwords requested changes

2024-08-23 19:38 UTC, thedriftofwords commented on src/content/tools/en/chainlink.mdx
> +You can find contract addresses for Chainlink on [Scroll Mainnet](https://docs.chain.link/).
```suggestion
You can find contract addresses for Chainlink for Scroll Mainnet and Scroll Sepolia testnet:

- [LINK Token Contracts for Scroll](https://docs.chain.link/resources/link-token-contracts#scroll)
- [L2 Sequencer Data Feeds](https://docs.chain.link/data-feeds/l2-sequencer-feeds#available-networks)
- [Price Feed Addresses for Scroll](https://docs.chain.link/data-feeds/price-feeds/addresses?network=scroll&page=1)


```

2024-08-23 19:47 UTC, thedriftofwords commented
@dghelm thanks for the suggestions. I've added links to the sections of the Chainlink docs that contain the info you asked for. We prefer to use docs links instead of including the addresses directly, so that you have the link to the latest info in case anything changes in the future.

2024-08-26 13:21 UTC, emilyJLin95 commented on src/content/tools/en/chainlink.mdx
> +You can find contract addresses for Chainlink on [Scroll Mainnet](https://docs.chain.link/).
Can you merge in this change? And hten I can approve

2024-08-28 13:50 UTC, emilyJLin95 approved these changes
LGTM

2024-08-28 16:09 UTC, thedriftofwords approved these changes

2024-08-29 04:03 UTC, ChuhanJin approved these changes

2024-08-29 04:04 UTC, merged